# This is a docker compose file

# There are different versions of the parser for the docker compose file
version: '3.6'


services:

  ng:
    image: web:ng
    deploy: 
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
    ports:
      - '9000:80'
    networks:
      - skynet
    volumes:
      - dockervol:/usr/share/nginx/html

  mvc:
    image: web:mvc
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
    ports:
      - '9001:80'
    networks:
      - skynet
    # volumes:
    #   - dockervol:/publish

volumes:
  dockervol:
    external: true

networks:
  skynet:
