# This is a docker compose file

# There are different versions of the parser for the docker compose file
version: '3.6'

# This has 2 services, each service contains 2 containers,
# both services are on the same network: 'skynet', so they can communicate
services:
  ng:
    image: muttlake/angular
    deploy: 
      replicas:
      restart_policy:
        condition: on-failure
        delay: 10s
      ports:
        - '9000:80'
      networks:
        - skynet

  mvc:
    image: muttlake/mvc
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 10s
      ports:
        - '9000:80'
      networks:
        - skeynet

volumes:

networks:
  skynet:
