// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WeatherApp.DataSvc.WeatherApp.DB;

namespace WeatherApp.DB.Migrations
{
    [DbContext(typeof(WeatherAppContext))]
    [Migration("20180415010815_WeatherAppMig8")]
    partial class WeatherAppMig8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeatherApp.DataSvc.WeatherApp.DB.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlogPost");

                    b.Property<string>("ImageFile");

                    b.Property<DateTime>("PublishDateTime");

                    b.Property<int>("TempFahr");

                    b.Property<int>("UserID");

                    b.Property<string>("WeatherJson");

                    b.Property<string>("WeatherType");

                    b.Property<int>("ZipCode");

                    b.HasKey("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("WeatherApp.DataSvc.WeatherApp.DB.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<int>("HomeZipCode");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WeatherApp.DataSvc.WeatherApp.DB.Post", b =>
                {
                    b.HasOne("WeatherApp.DataSvc.WeatherApp.DB.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
