// <auto-generated />
using FoodRanker.Client;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FoodRanker.Client.Migrations
{
    [DbContext(typeof(FoodRankerContext))]
    [Migration("20180407172124_FoodRanker3")]
    partial class FoodRanker3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodRanker.Library.Food", b =>
                {
                    b.Property<int>("FoodID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AverageRank");

                    b.Property<int?>("FoodTypeID");

                    b.Property<string>("Name");

                    b.Property<int?>("RankingID");

                    b.HasKey("FoodID");

                    b.HasIndex("FoodTypeID");

                    b.HasIndex("RankingID");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FoodRanker.Library.FoodType", b =>
                {
                    b.Property<int>("FoodTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("FoodTypeID");

                    b.ToTable("FoodTypes");
                });

            modelBuilder.Entity("FoodRanker.Library.Ranking", b =>
                {
                    b.Property<int>("RankingID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("UserID");

                    b.HasKey("RankingID");

                    b.HasIndex("UserID");

                    b.ToTable("Rankings");
                });

            modelBuilder.Entity("FoodRanker.Library.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodRanker.Library.Food", b =>
                {
                    b.HasOne("FoodRanker.Library.FoodType", "FoodType")
                        .WithMany()
                        .HasForeignKey("FoodTypeID");

                    b.HasOne("FoodRanker.Library.Ranking")
                        .WithMany("Foods")
                        .HasForeignKey("RankingID");
                });

            modelBuilder.Entity("FoodRanker.Library.Ranking", b =>
                {
                    b.HasOne("FoodRanker.Library.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
