node 
{
    stage ('Import')
    {
        git url: 'https://github.com/1803-mar12-net/tim-code.git', branch: 'master', credentialId: 'github-token'
    }

    stage ('Build')
    {
        dir ('Adworks/')
        {
            bat 'dotnet build'
        }
    }
}